version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven
      - apt-get update
      - apt-get install -y maven

  pre_build:
    commands:
      - echo Running unit tests
      - mvn test

  build:
    commands:
      - echo Building the project
      - mvn clean package -DskipTests=true

artifacts:
  files:
    - target/pipelinecodare.jar

cache:
  paths:
    - '/root/.m2/**/*'