server.port=5000

spring.datasource.url=jdbc:mysql://new.nilelines.com:3306/serv20in_majdi?useSSL=true&serverTimezone=UTC
spring.datasource.username=serv20in_majdi
spring.datasource.password=qwm

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect

logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG